name: MLOps

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  train-and-report:
    # (configuration du job train-and-report comme avant)
  
  publish-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: pip install --requirement requirements-freeze.txt

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

      - name: Check model
        run: dvc repro --pull

      - name: Log in to the Container registry
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin europe-west6-docker.pkg.dev

      - name: Import the BentoML model
        run: bentoml models import model/celestial_bodies_classifier_model.bentomodel

      - name: Build the BentoML model artifact
        run: bentoml build src

      - name: Containerize and publish the BentoML model artifact Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          bentoml containerize celestial_bodies_classifier:latest \
            --image-tag europe-west6-docker.pkg.dev/mlops-project-0710/v2-mlops-vural-registry/celestial-bodies-classifier:latest \
            --image-tag europe-west6-docker.pkg.dev/mlops-project-0710/v2-mlops-vural-registry/celestial-bodies-classifier:${{ github.sha }}
          docker push europe-west6-docker.pkg.dev/mlops-project-0710/v2-mlops-vural-registry/celestial-bodies-classifier:latest
          docker push europe-west6-docker.pkg.dev/mlops-project-0710/v2-mlops-vural-registry/celestial-bodies-classifier:${{ github.sha }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update the Kubernetes deployment
        run: |
          yq -i '.spec.template.spec.containers[0].image = "europe-west6-docker.pkg.dev/mlops-project-0710/v2-mlops-vural-registry/celestial-bodies-classifier:${{ github.sha }}"' kubernetes/deployment.yaml

      - name: Get Google Cloud's Kubernetes credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GCP_K8S_CLUSTER_NAME }}
          location: ${{ secrets.GCP_K8S_CLUSTER_ZONE }}

      - name: Deploy the model on Kubernetes
        run: |
          kubectl apply \
            -f kubernetes/deployment.yaml \
            -f kubernetes/service.yaml
